version: '2'
services:
  database:
    image: "mysql:latest"
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: basketballdb
    volumes:
      - ./mysql:/var/lib/mysql

volumes:
  mysql:
