server:
  port: 8010
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 618607592835-61s1tp01k2njbj1fu7kar2ubsnu8i4p3.apps.googleusercontent.com
            client-secret: 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
  datasource:
    url: jdbc:mysql://localhost:3310/basketballdb
    username: root
    password: Adesso_346107d
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    #   https://docs.spring.io/spring-boot/docs/current/reference/html/howto-database-initialization.html
    #    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3310/basketballdb?useMysqlMetadata=true
    locations: classpath:db/migration
    user: root
    password: Adesso_346107d
    flyway.schemas: basketballdb
    baseline-on-migrate: true